### ISSUE TITLE
Import from server doesn't work

### ISSUE THREAD

**Issue by zacheusz** [jkan997/SlingBeans#12]
1. make change (JSP file) in Sling Explorer view
2. switch to Projects, select the same file in Sling Content
3. select from context menu "import from server"

The tree under Sling Content is collapsing, Sling Synchronization plugin outputs "Imported /filePath from remote server /sling/http/localhost/4502", but the local file remains unchanged.

**Comment by zacheusz** [comment]
if I select "Import From Server" on the folder (one level up) then it works, but the tree is colapsing

**Comment by jkan997** [comment]
Fixed in version 1.1
