### ISSUE TITLE
wrong message while importing from server

### ISSUE THREAD

**Issue by zacheusz** [jkan997/SlingBeans#14]
Sling Content->Import from server
the message says "Exporting to remote"
![screen shot 2016-01-28 at 16 19 40](https://cloud.githubusercontent.com/assets/4950449/12648645/3d9d6014-c5db-11e5-8ff8-c72ff290093f.png)

**Comment by jkan997** [comment]
Confirmed

2016-01-28 20:52 GMT+05:30 zacheusz <notifications@github.com>:

**Comment by jkan997** [comment]
Fixed in version 1.1
